"""Pure preflop core for the punisher archetypes (bots/archetype_bot.py
``tag_punisher`` and ``wide_defender``).

One PURE decision function, `preflop_intent`, parameterised by a knob
struct (`PunisherKnobs`) so several archetype presets share the same
core without drift. The real-table adapter (`TagPunisherPolicy`) maps
its intents onto engine actions.

Determinism contract: this module draws ZERO randomness from any module
or bot RNG stream. Preflop strength comes from the committed 169-class
equity table (`bots/punisher_equity.py`, generated by
``python -m bots.punisher --regen`` from a private fixed-seed RNG);
mixed-frequency behavior (trap / marginal continue / re-steal) uses
keyed md5 hashing — never ``random`` and never the builtin ``hash()``
(which is salted per process).

Policy shape (thresholds are knobs): tight-aggressive punisher — fold
junk to aggression, open and value-raise a strong range, defend by pot
odds with a percentile gate that tightens as the price rises. The
percentile gates are derived from the equity table itself per live
opponent count, so multiway ordering shifts (suited connectors rising)
are automatic.
"""

from __future__ import annotations

import hashlib
from typing import Dict, List, NamedTuple, Optional, Tuple

RANKS = "23456789TJQKA"
_RANK_TO_INT = {r: i for i, r in enumerate(RANKS)}

# ── Knobs ────────────────────────────────────────────────────────────────
# Module-level constants are the TAG preset. They are folded into
# TAG_PUNISHER ONCE at import and are NOT read live afterwards; to vary a
# preset at runtime (e.g. a zero-mix variant for a deterministic check),
# swap the PRESETS entry (see the registry below) instead of touching
# these constants.
OPEN_PCT = 0.22          # open-raise: top 22% of deal mass
VALUE_PCT = 0.08         # re-raise/jam for value: top 8%
CONT_PCT_SMALL = 0.34    # continue vs req < 0.25 (min-raise scale)
CONT_PCT_BIG = 0.26      # continue vs 0.25 <= req < 0.40 (pot-open/3-bet)
CONT_PCT_JAM = 0.12      # continue vs req >= 0.40 (jam scale)
DELTA = 0.05             # pot-odds margin: continue also needs eq >= req+DELTA
MARGIN_PCT = 0.05        # marginal-fold window above the continue gate
TRAP_FREQ = 0.15         # value re-raises that flat-call instead
LOOSE_FREQ = 0.10        # marginal folds that continue instead
JAM_SPR = 1.5            # at/below this stack-to-pot ratio, raises become jams


class PunisherKnobs(NamedTuple):
    """Per-preset knob struct. Immutable; preflop_intent takes one so the
    tag punisher and the wide defender share the same pure core without
    drift."""
    OPEN_PCT: float
    VALUE_PCT: float
    CONT_PCT_SMALL: float
    CONT_PCT_BIG: float
    CONT_PCT_JAM: float
    DELTA: float
    MARGIN_PCT: float
    TRAP_FREQ: float
    LOOSE_FREQ: float
    JAM_SPR: float
    RESTEAL_FREQ: float = 0.0  # share of non-value continues (req < 0.40)
    #                            upgraded to a re-raise (wide_defender)


# tag_punisher: the constants above, folded ONCE at import
# (RESTEAL_FREQ=0.0 — tag never re-steals) and registered in PRESETS.
TAG_PUNISHER = PunisherKnobs(
    OPEN_PCT=OPEN_PCT, VALUE_PCT=VALUE_PCT,
    CONT_PCT_SMALL=CONT_PCT_SMALL, CONT_PCT_BIG=CONT_PCT_BIG,
    CONT_PCT_JAM=CONT_PCT_JAM, DELTA=DELTA,
    MARGIN_PCT=MARGIN_PCT, TRAP_FREQ=TRAP_FREQ,
    LOOSE_FREQ=LOOSE_FREQ, JAM_SPR=JAM_SPR, RESTEAL_FREQ=0.0)

# wide_defender: same pure core, price-sensitive WIDER defense vs raises
# + hash-mixed re-steals; jam defense stays as tight as tag (pot-odds
# honesty). Values were tuned against the deterministic 169-grid to
# calibration windows (fold vs pot-open 45-60%, fold vs 100bb jam
# 80-90%, context-weighted VPIP 24-36%, raise share of entries >= 50%,
# deep open-jam <= 2%, re-steal share of defends 8-20%), then frozen.
WIDE_DEFENDER = PunisherKnobs(
    OPEN_PCT=0.26,
    VALUE_PCT=0.08,
    CONT_PCT_SMALL=0.48,
    CONT_PCT_BIG=0.45,
    CONT_PCT_JAM=0.12,
    DELTA=0.03,
    MARGIN_PCT=0.05,
    TRAP_FREQ=0.15,
    LOOSE_FREQ=0.10,
    JAM_SPR=1.5,
    RESTEAL_FREQ=0.12,
)

# Preset registry (insertion order: tag first). Every preset lives here
# and every lookup reads the dict LIVE, so a caller may swap an entry for
# a deterministic check — e.g. PRESETS["tag_punisher"] =
# TAG_PUNISHER._replace(TRAP_FREQ=0.0, LOOSE_FREQ=0.0) — and restore it
# in ``finally``.
PRESETS: Dict[str, PunisherKnobs] = {
    "tag_punisher": TAG_PUNISHER,
    "wide_defender": WIDE_DEFENDER,
}
PRESET_NAMES = tuple(PRESETS)


def preset_knobs(name: str) -> PunisherKnobs:
    """Resolve a preset name to its knob struct — a live PRESETS lookup,
    so registry swaps are honored. ValueError on unknown."""
    try:
        return PRESETS[name]
    except KeyError:
        raise ValueError(
            f"unknown punisher preset {name!r}; expected one of "
            f"{PRESET_NAMES}") from None


_TOTAL_COMBOS = 1326.0


def class_key(hole) -> Tuple[int, int, bool]:
    """Canonical 169-class key (high_rank, low_rank, suited) for 2 cards."""
    r1 = _RANK_TO_INT[str(hole[0][0])]
    r2 = _RANK_TO_INT[str(hole[1][0])]
    high, low = max(r1, r2), min(r1, r2)
    suited = str(hole[0][1]) == str(hole[1][1]) and r1 != r2
    return (high, low, suited)


def _combos(key: Tuple[int, int, bool]) -> int:
    high, low, suited = key
    if high == low:
        return 6
    return 4 if suited else 12


def _load_table() -> Dict[Tuple[int, int, bool], Tuple[float, ...]]:
    try:
        from bots.punisher_equity import PREFLOP_EQUITY
    except ImportError as e:  # pragma: no cover - regen instruction
        raise ImportError(
            "bots/punisher_equity.py missing — generate it once with "
            "`python -m bots.punisher --regen` (fixed-seed, committed)"
        ) from e
    if len(PREFLOP_EQUITY) != 169:
        raise ValueError(
            f"punisher equity table has {len(PREFLOP_EQUITY)} classes, "
            f"expected 169 — regenerate with `python -m bots.punisher "
            f"--regen`"
        )
    return PREFLOP_EQUITY


# Lazily initialized on first use so `python -m bots.punisher --regen`
# can bootstrap the table module before it exists.
_EQUITY: Dict[Tuple[int, int, bool], Tuple[float, ...]] = {}
# Percentile map per live-opponent count: fraction of total deal mass in
# classes with STRICTLY better table equity (AA -> 0.0). Deterministic:
# ties broken by class key.
_PERCENTILE: List[Dict[Tuple[int, int, bool], float]] = []


def _ensure_tables() -> None:
    if _EQUITY:
        return
    _EQUITY.update(_load_table())
    for k in range(5):
        order = sorted(_EQUITY.items(), key=lambda kv: (-kv[1][k], kv[0]))
        seen = 0.0
        pct: Dict[Tuple[int, int, bool], float] = {}
        for key, _ in order:
            pct[key] = seen / _TOTAL_COMBOS
            seen += _combos(key)
        _PERCENTILE.append(pct)


def class_equity(key: Tuple[int, int, bool], n_opp: int) -> float:
    """Preflop equity vs n_opp random hands (committed table)."""
    _ensure_tables()
    n = max(1, min(5, int(n_opp)))
    return _EQUITY[key][n - 1]


def class_percentile(key: Tuple[int, int, bool], n_opp: int) -> float:
    """Deal-mass share of strictly-better classes at this opponent count."""
    _ensure_tables()
    n = max(1, min(5, int(n_opp)))
    return _PERCENTILE[n - 1][key]


def stable_frac(*parts) -> float:
    """Keyed deterministic uniform in [0, 1) — md5, zero RNG stream use."""
    text = "|".join(str(p) for p in parts)
    digest = hashlib.md5(text.encode("utf-8")).digest()
    return int.from_bytes(digest[:8], "big") / float(1 << 64)


def preflop_intent(key: Tuple[int, int, bool], *, n_opp: int, req: float,
                   facing_raise: bool, free_check: bool, spr: float,
                   mix=None, knobs: Optional[PunisherKnobs] = None) -> str:
    """Pure preflop decision: 'fold' | 'check' | 'call' | 'raise' | 'jam'.

    req: to_call / (pot + to_call); facing_raise: someone has bet/raised
    this preflop beyond the blinds — the adapter derives it from the
    visible history (any preflop bet/raise/all_in), NEVER from an
    inferred big blind; free_check: to_call == 0; spr: actor stack / pot;
    mix: optional callable ``mix(tag, freq) -> bool`` implementing the
    deterministic trap/loose/resteal hash-mix (None disables all mixing,
    which yields the base frequencies). The adapter supplies its own
    keyed-hash mix so frequencies, not per-state draws, are the
    contract. knobs: per-preset thresholds; None reads the tag preset
    LIVE from PRESETS, so a registry swap applies here too.
    """
    k = knobs if knobs is not None else PRESETS["tag_punisher"]
    pct = class_percentile(key, n_opp)
    eq = class_equity(key, n_opp)

    if not facing_raise:
        # Unopened / limped / free option. Never open-limp: raise the
        # opening range, otherwise take a free check or fold to the
        # (partial-blind) price.
        if pct <= k.OPEN_PCT:
            return "jam" if spr <= k.JAM_SPR else "raise"
        return "check" if free_check else "fold"

    # Facing live aggression: percentile gate tightens with the price,
    # plus the pot-odds margin (eq >= req + DELTA).
    if req >= 0.40:
        thr = k.CONT_PCT_JAM
    elif req >= 0.25:
        thr = k.CONT_PCT_BIG
    else:
        thr = k.CONT_PCT_SMALL

    def _continue():
        # Non-value continue; wide_defender upgrades a hash-mixed share
        # of these to a re-steal vs sub-jam prices so blanket steals
        # stop printing fold equity.
        if (req < 0.40 and k.RESTEAL_FREQ > 0.0 and mix is not None
                and mix("resteal", k.RESTEAL_FREQ)):
            return "jam" if spr <= k.JAM_SPR else "raise"
        return "call"

    if pct <= k.VALUE_PCT:
        if mix is not None and mix("trap", k.TRAP_FREQ):
            return "call"                       # slow-play: punishes barrels
        return "jam" if spr <= k.JAM_SPR else "raise"
    if pct <= thr and eq >= req + k.DELTA:
        return _continue()
    if (pct <= thr + k.MARGIN_PCT and eq >= req and mix is not None
            and mix("loose", k.LOOSE_FREQ)):
        return _continue()                      # marginal continue mix
    return "fold"


# ── Equity-table generator (`python -m bots.punisher --regen`) ──────────

def _generate_table(n_sims: int = 4000) -> Dict[Tuple[int, int, bool],
                                                Tuple[float, ...]]:
    """Monte-Carlo the 169 x n_opp preflop equity table with a PRIVATE
    fixed-seed RNG per class (module `random` state untouched). One pass
    deals 5 opponents + board per sim; the first k opponent hands give
    the vs-k sample, so all five columns share the draws (each column
    unbiased). Tie value = hero's pot share, 1 / (1 + tying opponents).
    """
    import random as _random
    from core.engine import _FULL_DECK, eval_hand

    table: Dict[Tuple[int, int, bool], Tuple[float, ...]] = {}
    for high in range(13):
        for low in range(high + 1):
            variants = [False] if high == low else [False, True]
            for suited in variants:
                key = (high, low, suited)
                hero = [(RANKS[high], "s"),
                        (RANKS[low], "s" if suited else "h")]
                rng = _random.Random(
                    ((high * 13 + low) * 2 + int(suited)) ^ 0x5EEDF00D)
                deck = [c for c in _FULL_DECK
                        if c not in {tuple(x) for x in hero}]
                share_sums = [0.0] * 5
                for _ in range(n_sims):
                    drawn = rng.sample(deck, 15)
                    board = drawn[10:15]
                    hero_score = eval_hand(hero, board)
                    opp_scores = [
                        eval_hand(drawn[2 * i:2 * i + 2], board)
                        for i in range(5)
                    ]
                    best, ties = -1, 0
                    for k in range(5):
                        s = opp_scores[k]
                        if s > best:
                            best, ties = s, 1
                        elif s == best:
                            ties += 1
                        if hero_score > best:
                            share_sums[k] += 1.0
                        elif hero_score == best:
                            share_sums[k] += 1.0 / (1.0 + ties)
                table[key] = tuple(
                    round(s / n_sims, 5) for s in share_sums)
    return table


def _write_table_module(path: str, n_sims: int) -> None:
    table = _generate_table(n_sims)
    lines = [
        '"""Committed preflop equity table for the punisher archetypes.',
        "",
        f"GENERATED by `python -m bots.punisher --regen` (n_sims={n_sims},",
        "fixed per-class seeds — regenerating reproduces this file",
        "byte-for-byte). Values: hero pot-share equity vs 1..5 random",
        'hands, per canonical class (high_rank, low_rank, suited)."""',
        "",
        "PREFLOP_EQUITY = {",
    ]
    for key in sorted(table):
        lines.append(f"    {key!r}: {table[key]!r},")
    lines.append("}")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    import argparse
    import os
    import sys

    sys.path.insert(0, os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))))
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--regen", action="store_true",
                    help="regenerate bots/punisher_equity.py")
    ap.add_argument("--sims", type=int, default=4000)
    args = ap.parse_args()
    if args.regen:
        out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "punisher_equity.py")
        _write_table_module(out, args.sims)
        print(f"wrote {out}")
    else:
        ap.print_help()
